name: Deploy
on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read
jobs:
  build:
    uses: rollthecloudinc/quell/.github/workflows/azure-workflow.yml@master
    with:
      ENVIRONMENT: prod
    secrets:
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}